	public void foo2() throws java.rmi.ConnectException {
	}

