//https://bugs.eclipse.org/bugs/show_bug.cgi?id=248319
public void test067() throws Exception {
	this.runConformTest(
			new String[] {
				"X.java",
				"public class X {\n" + 
				"	public static void main(final String[] args) {\n" + 
				"		System.out.println(new X().verifyError());\n" + 
				"	}\n" + 
				"	private Object verifyError() {\n" + 
				"		try {\n" + 
				"			if (someBooleanMethod()) {\n" + 
				"				return null;\n" + 
				"			}\n" + 
				"			return getStuff();\n" + 
				"		} catch (final Exception ex) {\n" + 
				"			return null;\n" + 
				"		} finally {\n" + 
				"			while (someBooleanMethod()) {\n" + 
				"				anyMethod();\n" + 
				"			}\n" + 
				"		}\n" + 
				"	}\n" + 
				"	private void anyMethod() { /*empty*/ }\n" + 
				"	private Object getStuff() { return null; }\n" + 
				"	private boolean someBooleanMethod() { return false; }\n" + 
				"}\n" + 
				"",
			},
			"null");
}

